In [1]:
import pyspark
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession

spark = SparkSession.builder\
    .appName("test")\
    .master("local")\
    .enableHiveSupport()\
    .getOrCreate()

In [2]:
df = spark.read.json("data/*.jsonl")

In [3]:
import pyspark.sql.functions as func

pdf = df.filter(func.col("layers.dns.text_dns_qry_name").isNotNull())\
    .select(
        [
            "layers.dns.text_dns_qry_name",
            "layers.ip.ip_ip_dst_host"
        ]
    ).toPandas()

In [4]:
pdf

                  text_dns_qry_name ip_ip_dst_host
0                    www.10news.com     10.5.5.155
1               s.skimresources.com     10.5.5.155
2       ewscripps.brightspotcdn.com     10.5.5.155
3              static.chartbeat.com     10.5.5.155
4     d25dfknw9ghxs6.cloudfront.net     10.5.5.155
...                             ...            ...
2982                 www.google.com    10.15.5.175
2983                 www.google.com    10.15.5.175
2984                 www.google.com    10.15.5.175
2985                   wo.vzwwo.com     10.5.5.158
2986                         aka.ms    10.95.5.101

[2987 rows x 2 columns]

In [5]:
pdf = df.filter(func.col("layers.dns.text_dns_qry_name").isNotNull())\
    .select(
        [
            "layers.dns.text_dns_qry_name",
            "layers.ip.ip_ip_dst_host"
        ]
    ).toPandas()

In [6]:
dns = df.filter(func.col("layers.dns.text_dns_qry_name").isNotNull())
dns.groupBy("layers.ip.ip_ip_dst_host")\
    .agg(func.countDistinct("layers.dns.text_dns_qry_name").alias("qry_name_count"))\
    .sort(func.desc("qry_name_count"))\
    .toPandas()

   ip_ip_dst_host  qry_name_count
0      10.5.5.155             407
1      10.5.5.161             183
2     10.95.5.101             146
3      10.5.5.182             118
4      10.5.5.158              73
5      10.5.5.160              49
6      10.5.5.194              42
7      10.5.5.156              33
8      10.5.5.178              29
9      10.5.5.159              29
10     10.5.5.154              25
11     10.5.5.157              11
12    10.95.5.103               7
13    10.15.5.159               6
14     10.5.5.181               6
15    10.15.5.175               6
16    10.15.5.161               5
17    10.15.5.171               3
18    10.15.5.170               2
19    10.15.5.162               2
20    10.15.5.167               2
21    10.15.5.163               2
22    10.15.5.155               2
23    10.15.5.169               1
24    10.15.5.160               1